### ISSUE TITLE
The Orleans/WebApp setup fails when try to deploy on Staging slot 

### ISSUE THREAD

**Issue by ArunBee84** [Azure-Samples/Orleans-Cluster-on-Azure-App-Service#3]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Follow the steps mentioned on Microsoft docs [here](https://learn.microsoft.com/en-us/dotnet/orleans/deployment/deploy-to-azure-app-service). Then create a Staging slot copying the production slot configuration and deploy the same Silo.zip.

### Any log messages given by the failure
>Exception while sending message: Orleans.Runtime.Messaging.ConnectionFailedException: Unable to connect to endpoint S172.17.0.254:20026:409928338. See InnerException
 ---> Orleans.Networking.Shared.SocketConnectionException: Unable to connect to 172.17.0.254:20026. Error: AccessDenied
   at Orleans.Networking.Shared.SocketConnectionFactory.ConnectAsync(EndPoint endpoint, CancellationToken cancellationToken) in /_/src/Orleans.Core/Networking/Shared/SocketConnectionFactory.cs:line 52
   at Orleans.Runtime.Messaging.ConnectionFactory.ConnectAsync(SiloAddress address, CancellationToken cancellationToken) in /_/src/Orleans.Core/Networking/ConnectionFactory.cs:line 53
   at Orleans.Runtime.Messaging.ConnectionManager.ConnectAsync(SiloAddress address) in /_/src/Orleans.Core/Networking/ConnectionManager.cs:line 293
   --- End of inner exception stack trace ---
   at Orleans.Runtime.Messaging.ConnectionManager.ConnectAsync(SiloAddress address) in /_/src/Orleans.Core/Networking/ConnectionManager.cs:line 293
   at Orleans.Runtime.Messaging.ConnectionManager.GetConnectionAsync(SiloAddress endpoint) in /_/src/Orleans.Core/Networking/ConnectionManager.cs:line 139
   at Orleans.Runtime.Messaging.OutboundMessageQueue.<SendMessage>g__SendAsync|10_0(ValueTask`1 c, Message m) in /_/src/Orleans.Runtime/Messaging/OutboundMessageQueue.cs:line 130 

### Expected/desired behavior
> The Silo instance should be able to communicate with the production Silo instance 

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> The Production Silo instance is running on 172.17.0.254:20026. I tried to tcpping this from Staging Slot KUDU and got the following error:
PS C:\home> tcpping 172.17.0.254:20026
tcpping 172.17.0.254:20026
Connection attempt failed: An attempt was made to access a socket in a way forbidden by its access permissions 172.17.0.254:20026

> Thanks! We'll be in touch soon.

**Comment by IEvangelist** [comment]
Looks like @bradygaster figured out a solution to this issue here:
https://github.com/Azure-Samples/Orleans-Cluster-on-Azure-App-Service/compare/main...bradygaster:Orleans-Cluster-on-Azure-App-Service:slots

**Comment by bradygaster** [comment]
Well - it's one approach. :) Speaking of what - we should chat and figure out our process for updating the doc and sample with this stuff.

**Comment by IEvangelist** [comment]
Hey @bradygaster - correct me if I'm wrong, but I believe this issue can be closed by the recent PR that was merged here, no?

See https://github.com/Azure-Samples/Orleans-Cluster-on-Azure-App-Service/pull/5

**Comment by bradygaster** [comment]
Yes I believe that's correct. There were some issues related to slots we can't resolve atm, like having both slots on the same subnet or migrating, but I do believe this can be closed, so closing.
